config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :sessions, only: [ :new, :create, :destroy ]
  resources :departments
  resources :participants do
    resources :steps, only: [ :new, :create, :edit, :destroy ]
  end

  root 'static_pages#home'
  match '/signup', to: "users#new", via: 'get'
  match '/signin', to: "sessions#new", via: 'get'
  match '/signout', to: "sessions#destroy", via: 'delete'
end

app/models/department.rb
class Department < ActiveRecord::Base
  has_many :participants
  default_scope -> { order('name ASC') }
  validates :name, presence: true, uniqueness: true, length: { maximum: 100 }

  def self.total
    sum(:participants)
  end
end

app/models/participant.rb
class Participant < ActiveRecord::Base
  belongs_to :department
  validates :department_id, presence: true
  has_many :steps, dependent: :destroy
end

app/models/step.rb
class Step < ActiveRecord::Base
  belongs_to :participant
  default_scope -> { order('date DESC') }
  validates :participant_id, presence: true
  validates :num_steps, presence: true, numericality: { only_integer: true, less_than: 100000 }

  def self.total
    sum(:num_steps)
  end

  def self.avg
    average(:num_steps).to_i
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  before_save { self.email = email.downcase }
  before_create :create_remember_token

  validates :name, presence: true, length: { maximum: 50 }
  validates :email, presence: true, uniqueness: { case_sensitive: false }, format: { with: VALID_EMAIL_REGEX }

  has_secure_password
  validates :password, length: { minimum: 6 }

  def User.new_remember_token
    SecureRandom.urlsafe_base64
  end

  def User.encrypt(token)
    Digest::SHA1.hexdigest(token.to_s)
  end

  private

  def create_remember_token
    self.remember_token = User.encrypt(User.new_remember_token)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/departments_controller.rb
class DepartmentsController < ApplicationController
  before_action :signed_in_user

  def index
    @departments = Department.paginate(page: params[:page])
  end

  def show
    @department = Department.find(params[:id])
    @participants = @department.participants.paginate(page: params[:page])
    @total_steps = @participants.map { |p| p.steps.total }.sum
  end

  def new
    @department = Department.new
  end

  def create
    @department = Department.new(department)
    if @department.save
      redirect_to departments_url
    else
      render 'new'
    end
  end

  def edit
    @department = Department.find(params[:id])
  end

  def destroy
    Department.find(params[:id]).destroy
    flash.now[:success] = "Department successfully deleted"
    redirect_to departments_url
  end

  def update
    @department = Department.find_by_id(params[:id])
    if @department.update_attributes(department_params)
      flash.now[:success] = "Changes saved"
      redirect_to @department
    else
      render 'edit'
    end
  end

  private

  def department_params
    params.require(:department).permit(:name)
  end
end

app/controllers/participants_controller.rb
class ParticipantsController < ApplicationController
  before_action :signed_in_user

  def index
    @participants = Participant.paginate(page: params[:page])
  end

  def show
    @participant = Participant.find(params[:id])
    @steps = @participant.steps.paginate(page: params[:page])
    steps_json = @participant.steps

    respond_to do |format|
      format.html
      format.json { render :json => steps_json }
    end
  end

  def new
    @participant = Participant.new
  end

  def create
    @department = Department.find(params[:department_id])
    @participant = Participant.new(participant_params)
    if @participant.save
      redirect_to participants_url
    else
      render 'new'
    end
  end

  def edit
    @participant = Participant.find(params[:id])
  end

  def destroy
    Participant.find(params[:id]).destroy
    flash.now[:success] = "Participant successfully deleted"
    redirect_to participants_url
  end

  def update
    if @participant.update_attributes(participant_params)
      flash.now[:success] = "Changes saved"
      redirect_to @participant
    else
      render 'edit'
    end
  end

  private

  def participant_params
    params.require(:participant).permit(:name, :department_id)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      sign_in user
      redirect_back_or root_url
    else
      flash.now[:danger] = "Invalid email and/or password."
      render 'new'
    end
  end

  def destroy
    sign_out
    redirect_to root_url
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    if signed_in?
      @participants = Participant.all.sort { |a,b| b.steps.total <=> a.steps.total }.take(10)
    end
  end
end

app/controllers/steps_controller.rb
class StepsController < ApplicationController
  before_action :signed_in_user

  def index
  end

  def new
    @step = Step.new
  end

  def create
    @participant = Participant.find(params[:participant_id])
    @step = @participant.steps.build(steps_params)
    if @step.save
      flash.now[:success] = "Step created"
    end
    redirect_to participant_url(@participant)
  end

  def destroy
    @participant = Participant.find(params[:participant_id])
    @participant.step.destroy
    redirect_to root_url
  end

  private

  def steps_params
    params.require(:step).permit(:participant_id, :date, :num_steps)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :signed_in_user, only: [ :index, :show, :edit, :update ]
  before_action :admin_user, only: [ :destroy ]

  def index
    @users = User.paginate(page: params[:page])
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      sign_in @user
      redirect_to root_url
    else
      render 'new'
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def destroy
    User.find(params[:id]).destroy
    flash.now[:success] = "User successfully deleted"
    redirect_to users_url
  end

  def update
    @user = User.find_by_id(params[:id])
    if @user.update_attributes(user_params)
      flash.now[:success] = "Changes saved"
      redirect_to user_path(@user)
    else
      render 'edit'
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :admin, :email, :password, :password_confirmation)
  end

  def correct_user
    @user = User.find(params[:id])
    redirect_to(root_url) unless current_user?(@user)
  end

  def admin_user
    redirect_to(root_url) unless current_user.admin?
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def full_title(page_title)
    base_title = "InTouch Neovia Walking Challenge"
    base_title if page_title.empty?
    "#{base_title} | #{page_title}"
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def sign_in(user)
    remember_token = User.new_remember_token
    cookies.permanent[:remember_token] = remember_token
    user.update_attribute(:remember_token, User.encrypt(remember_token))
    self.current_user = user
  end

  def sign_out
    current_user.update_attribute(:remember_token, User.encrypt(User.new_remember_token))
    cookies.delete(:remember_token)
    self.current_user = nil
  end

  def signed_in?
    !current_user.nil?
  end

  def signed_in_user
    unless signed_in?
      store_location
      redirect_to signin_url, notice: "Please sign in."
    end
  end

  def current_user=(user)
    @current_user = user
  end

  def current_user
    remember_token = User.encrypt(cookies[:remember_token])
    @current_user ||= User.find_by(remember_token: remember_token)
  end

  def current_user?(user)
    user == current_user
  end

  def redirect_back_or(default)
    redirect_to(session[:return_to] || default)
    session.delete(:return_to)
  end

  def store_location
    session[:return_to] = request.url if request.get?
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/departments/edit.html.erb
<% provide(:title, 'Edit Department') %>
<h1>Edit Department</h1>

<div class="span6 offset3">
  <%= form_for @department, html: { class: 'form-horizontal' } do |f| %>
    <%= render 'shared/department_error_messages' %>

    <div class="form-group">
      <%= f.label :name, class: 'col-sm-2 control-label' %>
      <div class="col-sm-10">
        <%= f.text_field :name, class: 'form-control' %>
      </div>
    </div>

    <div class="form-group">
      <div class="col-sm-offset-2 col-sm-10">
        <%= f.submit 'Save', class: "btn btn-primary", id: "submit-button" %>
      </div>
    </div>
  <% end %>
</div>

app/views/departments/index.html.erb
<% provide(:title, 'Departments') %>
<h1>Departments</h1>

<%= will_paginate %>

<% if current_user.admin? %>
  <div class="span6 offset3">
    <%= link_to 'Add Department', new_department_path, class: 'btn btn-primary' %>
  </div>
<% end %>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Number of Participants</th>
      <th>Total Steps</th>
      <% if current_user.admin? %>
        <th></th>
      <% end %>
    </tr>
  </thead>
  <tbody>
  <% @departments.each do |department| %>
    <tr>
      <td><%= link_to department.name, department_path(department) %></td>
      <td><%= department.participants.count %></td>
      <td><%= number_with_delimiter(department.participants.map { |p| p.steps.total }.sum) %></td>
      <% if current_user.admin? %>
        <td>
          <%= link_to 'Edit', edit_department_path(department), class: 'btn btn-mini btn-default'  %>
          <%= link_to 'Delete', department, method: :delete, data: { confirm: "Are you sure you want to delete this department?" }, class: 'btn btn-mini btn-danger' %>
        </td>
      <% end %>
    </tr>
  <% end %>
  </tbody>
</table>

<%= will_paginate %>

app/views/departments/new.html.erb
<% provide(:title, 'New Department') %>
<h1>New Department</h1>

<div class="span6 offset3">
  <%= form_for @department, html: { class: 'form-horizontal' } do |f| %>
    <%= render 'shared/department_error_messages' %>

    <div class="form-group">
      <%= f.label :name, class:'col-sm-2 control-label' %>
      <div class="col-sm-10">
        <%= f.text_field :name, class: 'form-control', placeholder: 'Name' %>
      </div>
    </div>

    <div class="form-group">
      <div class="col-sm-offset-2 col-sm-10">
        <%= f.submit 'Create', class: "btn btn-primary", id: "submit-button" %>
      </div>
    </div>
  <% end %>
</div>

app/views/departments/show.html.erb
<% provide(:title, @department.name) %>
<h1><%= @department.name %></h1>

<% if @participants.any? %>
  <h2>Total participants: <%= @participants.count %> | Total steps: <%= number_with_delimiter(@total_steps) %></h2>
<% end %>

<% if current_user.admin? %>
  <div class="span6 offset3">
    <%= link_to 'Add Participant', new_participant_path(department_id: @department.id), class: 'btn btn-primary' %>
  </div>
<% end %>

<%= will_paginate @participants %>

<div class="span8">
  <% if @participants.any? %>
    <table class="table table-striped">
      <thead>
        <tr>
          <th>Name</th>
          <th>Total Steps</th>
          <th>Average Steps</th>
          <% if current_user.admin? %>
            <th></th>
          <% end %>
        </tr>
      </thead>
      <tbody>
      <% @participants.each do |participant| %>
        <tr>
          <td><%= link_to participant.name, participant_path(participant)  %></td>
          <td><%= number_with_delimiter(participant.steps.total) %></td>
          <td><%= number_with_delimiter(participant.steps.avg) %></td>
          <% if current_user.admin? %>
            <td>
              <%= link_to 'Edit', edit_participant_path(participant_id: participant.id), class: 'btn btn-mini btn-default' %>
              <%= link_to 'Delete', participant_path(participant_id: participant.id), method: :delete, data: { confirm: "Are you sure you want to delete this step?" }, class: 'btn btn-mini btn-danger' %>
            </td>
          <% end %>
        </tr>
      <% end %>
      </tbody>
    </table>
  <% end %>
</div>

<%= will_paginate @participants %>

app/views/layouts/_footer.html.erb
<footer class="footer">
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to "InTouch Neovia Walking Challenge", root_path, class: "brand", id: "logo" %>
      <nav>
        <ul class="nav navbar-nav pull-right">
          <li><%= link_to "Home", root_path %></li>
          <% if signed_in? %>
            <li><%= link_to "Departments", departments_path %></li>
            <li><%= link_to "Pariticpants", participants_path %></li>
            <li><%= link_to "Users", users_path %></li>
            <li id="fat-menu" class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown"> Account <b class="caret"></b></a>
              <ul class="dropdown-menu">
                <li><%= link_to "Profile", current_user %></li>
                <li><%= link_to "Settings", edit_user_path(current_user) %></li>
                <li class="divider"></li>
                <li><%= link_to "Sign out", signout_path, method: "delete" %></li>
              </ul>
            </li>
          <% else %>
            <li><%= link_to "Sign in", signin_path %></li>
          <% end %>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |key,value| %>
        <%= content_tag(:div, value, class: "alert alert-#{key}") %>
      <% end %>
      <%= yield %>
    </div>
    <%= render 'layouts/footer' %>
    <%= debug(params) if Rails.env.development? %>
  </body>
</html>

app/views/participants/edit.html.erb
<% provide(:title, 'Edit participant') %>
<h1>Change settings</h1>

<div class="span6 offset3">
  <%= form_for @participant, html: { class: 'form-horizontal' } do |f| %>
    <%= render 'shared/participant_error_messages' %>

    <div class="form-group">
      <%= f.label :name, class: 'col-sm-2 control-label' %>
      <div class="col-sm-10">
        <%= f.text_field :name, class: 'form-control' %>
      </div>
    </div>

    <div class="form-group">
      <div class="col-sm-offset-2 col-sm-10">
        <%= f.submit 'Save', class: "btn btn-primary", id: "submit-button" %>
      </div>
    </div>
  <% end %>
</div>

app/views/participants/index.html.erb
<% provide(:title, 'Participants') %>
<h1>Participants</h1>

<%= will_paginate %>

<% if current_user.admin? %>
  <div class="span6 offset3">
    <%= link_to 'Add Participant', new_participant_path, class: 'btn btn-primary' %>
  </div>
<% end %>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Total Steps</th>
      <th>Average Steps</th>
      <th>Department</th>
      <% if current_user.admin? %>
        <th></th>
      <% end %>
    </tr>
  </thead>
  <tbody>
  <% @participants.sort { |a,b| b.steps.total <=> a.steps.total}.each do |participant| %>
    <tr>
      <td><%= link_to participant.name, participant_path(participant) %></td>
      <td><%= number_with_delimiter(participant.steps.total) %></td>
      <td><%= number_with_delimiter(participant.steps.avg) %></td>
      <td><%= link_to participant.department.name, department_path(participant.department) %></td>
      <% if current_user.admin? %>
        <td>
          <%= link_to 'Edit', edit_participant_path(participant), class: 'btn btn-mini btn-default' %>
          <%= link_to 'Delete', participant, method: :delete, data: { confirm: "Are you sure you want to delete this user?" }, class: 'btn btn-mini btn-danger' %>
        </td>
      <% end %>
    </tr>
  <% end %>
  </tbody>
</table>

<%= will_paginate %>

app/views/participants/new.html.erb
<% provide(:title, 'New Participant') %>
<h1>New Participant</h1>

<div class="span6 offset3">
  <%= form_for @participant, html: { class: 'form-horizontal' } do |f| %>
    <%= render 'shared/participant_error_messages' %>

    <div class="form-group">
      <%= f.label :name, class:'col-sm-2 control-label' %>
      <div class="col-sm-10">
        <%= f.text_field :name, class: 'form-control', placeholder: 'Name' %>
      </div>
    </div>

    <div class="form-group">
      <div class="col-sm-offset-2 col-sm-10">
        <%= f.submit "Create participant", class: "btn btn-primary", id: "submit-button" %>
      </div>
    </div>
  <% end %>
</div>

app/views/participants/show.html.erb
<% provide(:title, @participant.name) %>
<h1><%= @participant.name %></h1>

<% if @steps.any? %>
  <h2>Total steps: <%= number_with_delimiter(@steps.total) %> | Average steps: <%= number_with_delimiter(@steps.avg) %></h2>
<% end %>

<div id="d3" class="span6 offset3">
</div>

<% if current_user.admin? %>
  <div class="span6 offset3">
    <%= link_to 'Add Steps', new_participant_step_path(participant_id: @participant.id), class: 'btn btn-primary' %>
  </div>
<% end %>

<%= will_paginate @steps %>

<div class="span8">
  <% if @steps.any? %>
    <table class="table table-striped">
      <thead>
        <tr>
          <th>Date</th>
          <th>Number of Steps</th>
          <% if current_user.admin? %>
            <th></th>
          <% end %>
        </tr>
      </thead>
      <tbody>
      <% @steps.each do |step| %>
        <tr>
          <td><%= step.date.to_date %></td>
          <td><%= number_with_delimiter(step.num_steps) %></td>
          <% if current_user.admin? %>
            <td>
              <%= link_to 'Edit', edit_participant_step_path(participant_id: @participant.id), class: 'btn btn-mini btn-default' %>
              <%= link_to 'Delete', participant_step_path(participant_id: @participant.id), method: :delete, data: { confirm: "Are you sure you want to delete this participant?" }, class: 'btn btn-mini btn-danger' %>
            </td>
          <% end %>
        </tr>
      <% end %>
      </tbody>
    </table>
  <% end %>
</div>

<%= will_paginate @steps %>

<%= javascript_tag do %>
  function getDate(d) {
    var date = new Date(d.date);
    date.setDate(date.getDate() + 1);
    date.setHours(0, 0, 0, 0);
    return date;
  }

  $(function() {
    var url = <%= @participant.id %> + '.json';
    d3.json(url, function(error, dataset) {
      var width = 960;
      var height = 250;

      var svg = d3.select("#d3")
        .append("svg:svg")
        .attr("viewBox", "0 0 " + width + " " + height);

      var padding = 50;

      var minDate = d3.min(dataset, function(d) { return getDate(d); });
      minDate.setDate(minDate.getDate() - 1);

      var maxDate = d3.max(dataset, function(d) { return getDate(d); });

      var xScale = d3.time.scale()
        .domain([minDate, maxDate])
        .range([padding, width - padding]);

      var yScale = d3.scale.linear()
        .domain([0, d3.max(dataset, function(d) { return d.num_steps; })])
        .range([height - padding, padding]);

      var format = d3.time.format("%d %b");
      var xAxis = d3.svg.axis()
        .scale(xScale)
        .orient("bottom")
        .tickFormat(format)
        .ticks(d3.time.days, 1);

      svg.append("g")
        .attr("class", "axis x-axis")
        .attr("transform", "translate(0," + (height - padding) + ")")
        .call(xAxis)
        .selectAll("text")
        .style("text-anchor", "end")
        .attr("dx", "-0.8em")
        .attr("dy", "-0.55em")
        .attr("transform", "rotate(-90)");

      var yAxis = d3.svg.axis()
        .scale(yScale)
        .orient("left")
        .tickFormat(function (d) { return d; })
        .tickSize(5, 5, 0)
        .ticks(5);

      svg.append("g")
        .attr("class", "axis y-axis")
        .attr("transform", "translate(" + padding + ",0)")
        .call(yAxis)
        .append("text")
        .attr("transform", "rotate(-90)")
        .attr("y", 6)
        .attr("dy", ".71em")
        .attr("x", "-5em")
        .style("text-anchor", "end")
        .text("Steps");

      var line = d3.svg.line()
        .x(function(d) {
          return xScale(getDate(d));
        })
        .y(function(d) {
          return yScale(d.num_steps);
        });

      svg.append("svg:path").attr("d", line(dataset));

      svg.selectAll("circle")
        .data(dataset)
        .enter()
        .append("circle")
        .attr("class", "data-point")
        .attr("cx", function(d) {
          return xScale(getDate(d));
        })
        .attr("cy", function(d) {
          return yScale(d.num_steps);
        })
        .attr("r", 5);
    });
  });
<%  end %>

app/views/shared/_department_error_messages.html.erb
<% if @department.errors.any? %>
  <div id="error_explanation">
    <ul>
      <% @department.errors.full_messages.each do |msg| %>
        <li>* <%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li>* <%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_participant_error_messages.html.erb
<% if @participant.errors.any? %>
  <div id="error_explanation">
    <ul>
      <% @participant.errors.full_messages.each do |msg| %>
        <li>* <%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_session_error_messages.html.erb
<% if @session.errors.any? %>
  <div id="error_explanation">
    <ul>
      <% @session.errors.full_messages.each do |msg| %>
        <li>* <%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_step_error_messages.html.erb
<% if @step.errors.any? %>
  <div id="error_explanation">
    <ul>
      <% @step.errors.full_messages.each do |msg| %>
        <li>* <%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/static_pages/home.html.erb
<% provide(:title, "Home") %>

<% if signed_in? %>
  <h1>Top 10 Participants</h1>

  <div class="span8">
    <% if @participants.any? %>
      <table class="table table-striped">
        <thead>
          <tr>
            <th>Rank</th>
            <th>Name</th>
            <th>Total Steps</th>
            <th>Steps Behind</th>
            <th>Department</th>
          </tr>
        </thead>
        <tbody>
        <% @participants.each_with_index do |participant, index| %>
          <tr>
            <td><%= index + 1 %></td>
            <td><%= link_to participant.name, participant_path(participant) %></td>
            <td><%= number_with_delimiter(participant.steps.total) %></td>
            <td><%= number_with_delimiter(@participants.first.steps.total - participant.steps.total) %></td>
            <td><%= link_to participant.department.name, department_path(participant.department) %></td>
          </tr>
        <% end %>
        </tbody>
      </table>
    <% end %>
  </div>
<% end %>

app/views/steps/edit.html.erb
<% provide(:title, 'Edit participant') %>
<h1>Change settings</h1>

<div class="span6 offset3">
  <%= form_for @participant, html: { class: 'form-horizontal' } do |f| %>
    <%= render 'shared/participant_error_messages' %>

    <div class="form-group">
      <%= f.label :name, class: 'col-sm-2 control-label' %>
      <div class="col-sm-10">
        <%= f.text_field :name, class: 'form-control' %>
      </div>
    </div>

    <div class="form-group">
      <div class="col-sm-offset-2 col-sm-10">
        <%= f.submit 'Save', class: "btn btn-primary", id: "submit-button" %>
      </div>
    </div>
  <% end %>
</div>

app/views/steps/new.html.erb
<% provide(:title, 'New Step') %>
<h1>New Step</h1>

<div class="span6 offset3">
  <%= form_for @step, url: participant_steps_path, html: { class: 'form-horizontal' } do |f| %>
    <%= render 'shared/step_error_messages' %>

    <%= f.hidden_field :participant_id, :value => params[:participant_id] %>

    <div class="form-group">
      <%= f.label :num_steps, class:'col-sm-2 control-label' %>
      <div class="col-sm-10">
        <%= f.text_field :num_steps, class: 'form-control', placeholder: '0' %>
      </div>
    </div>

    <div class="form-group">
      <%= f.label :date, class:'col-sm-2 control-label' %>
      <div class="col-sm-10">
        <div class="input-group date controls" data-date-format="YYYY-MM-DD HH:MM:ss" id="datetimepicker1">
          <%= f.text_field :date, class: 'form-control' %>
          <span class="input-group-addon">
            <span class="glyphicon glyphicon-calendar"></span>
          </span>
        </div>
      </div>
    </div>

    <script type="text/javascript">
      $(function() {
        $('#datetimepicker1').datetimepicker();
      });
    </script>

    <div class="form-group">
      <div class="col-sm-offset-2 col-sm-10">
        <%= f.submit "Create step", class: "btn btn-primary", id: "submit-button" %>
      </div>
    </div>
  <% end %>
</div>

app/views/users/edit.html.erb
<% provide(:title, 'Edit user') %>
<h1>Change settings</h1>

<div class="span6 offset3">
  <%= form_for @user, html: { class: 'form-horizontal' } do |f| %>
    <%= render 'shared/error_messages' %>

    <div class="form-group">
      <%= f.label :name, class: 'col-sm-2 control-label' %>
      <div class="col-sm-10">
        <%= f.text_field :name, class: 'form-control' %>
      </div>
    </div>

    <% if current_user.admin? %>
      <div class="form-group">
        <%= f.label :admin, class: 'col-sm-2 control-label' %>
        <div class="col-sm-10">
          <div class="checkbox">
            <%= f.check_box :admin %>
          </div>
        </div>
      </div>
    <% end %>

    <div class="form-group">
      <%= f.label :email, class: 'col-sm-2 control-label' %>
      <div class="col-sm-10">
        <%= f.text_field :email, class: 'form-control' %>
      </div>
    </div>

    <% if current_user?(@user) %>
      <div class="form-group">
        <%= f.label :password, class: 'col-sm-2 control-label' %>
        <div class="col-sm-10">
          <%= f.password_field :password, class: 'form-control' %>
        </div>
      </div>

      <div class="form-group">
        <%= f.label :password_confirmation, "Confirmation", class: 'col-sm-2 control-label' %>
        <div class="col-sm-10">
          <%= f.password_field :password_confirmation, class: 'form-control' %>
        </div>
      </div>
    <% end %>

    <div class="form-group">
      <div class="col-sm-offset-2 col-sm-10">
        <%= f.submit 'Save', class: "btn btn-primary", id: "submit-button" %>
      </div>
    </div>
  <% end %>
</div>

app/views/users/index.html.erb
<% provide(:title, 'Users') %>
<h1>Users</h1>

<%= will_paginate %>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <% if current_user.admin? %>
        <th>Admin</th>
        <th></th>
      <% end %>
    </tr>
  </thead>
  <tbody>
  <% @users.each do |user| %>
    <tr>
      <td><%= user.name %></td>
      <td><%= user.email %></td>
      <% if current_user.admin? %>
        <td><%= user.admin %></td>
        <td>
          <%= link_to 'Edit', edit_user_path(user), class: 'btn btn-mini btn-default'  %>
          <% if !current_user?(user) %>
            <%= link_to 'Delete', user, method: :delete, data: { confirm: "Are you sure you want to delete this user?" }, class: 'btn btn-mini btn-danger' %>
          <% end %>
        </td>
      <% end %>
    </tr>
  <% end %>
  </tbody>
</table>

<%= will_paginate %>